version "3.2"
services:
  php:
    build:
      context: './php/'
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: web_jinetes_php
      
  apache:
    build:
      context: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: web_jinetes_apache

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_DATABASE: "jinetes"
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user_name
      MYSQL_USER_PASSWORD_FILE: /run/secrets/mysql_user_password
    container_name: web_jinetes_mysql

networks:
  frontend:
  backend:

volumes:
  db_data:

secrets:
  mysql_root_password:
    file: ${PROJECT_ROOT}/src/secrets/secret_mysql_root_password
  mysql_user_name:
    file: ${PROJECT_ROOT}/src/secrets/secret_mysql_user_name
  mysql_user_password:
    file: ${PROJECT_ROOT}/src/secrets/secret_mysql_user_password